spring:
  application:
    name: API Products

  datasource:
    url: jdbc:h2:mem:products
    driver-class-name: org.h2.Driver
    username: sa
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
